### ISSUE TITLE
Installation completed. While activating the box, it gives error message

### ISSUE THREAD

**Issue by aranganr** [gregzaal/Gaffer#105]
![Gaffer](https://user-images.githubusercontent.com/46908739/56845224-8204f400-68db-11e9-8e53-1f9a5c0dee3d.png)

**Comment by gregzaal** [comment]
Not sure what could have caused this upon installation, try deleting this whole folder:

```
C:\Users\yourname\AppData\Roaming\Blender Foundation\Blender\data\gaffer
```

Also, does your `username` in that path above contain any characters that aren't in the English alphabet?

**Comment by Jordo86** [comment]
I have a similar issue too.
![Issue](https://user-images.githubusercontent.com/28997322/57119002-2688a980-6da6-11e9-8de1-2748fecb0126.png)

**Comment by gregzaal** [comment]
@Jordo86 that's a completely different issue - it looks like you've installed the Blender 2.8 version of Gaffer in Blender 2.7.

@aranganr It's been a week, closing this issue. If you still get that error let me know what you've tried.

**Comment by aranganr** [comment]
It is working now. Thanks.
