### ISSUE TITLE
Doesn’t Work

### ISSUE THREAD

**Issue by Peachypi** [gregzaal/Gaffer#106]
I’ve been using your add-on for a couple months, but now it doesn’t work, after a new update, all of it has disappeared, I tried removing it and reinstalling the add on, and even uninstalling and reinstalling Blender, I’ve tried this on two different Laptops (both running Blender 2.79b) and nothing has worked (and, yes I tried both installing the add on from the zip file, and unzipping the file and putting it in the Addons folder)

**Comment by gregzaal** [comment]
The latest version of Gaffer only works in Blender 2.8. You'll need to use an [older version](https://github.com/gregzaal/Gaffer/archive/v3.0.5.zip) (and possibly disable the automatic updates) in order to use it in Blender 2.7x
