### ISSUE TITLE
Module not found: gpu_extras

### ISSUE THREAD

**Issue by paperbenni** [gregzaal/Gaffer#109]
This error message pops up when I try to enable gaffer. The issue occurs both with the latest release and master. 
System info:
Blender 2.79 build-bot and release tested
OS: Arch Linux
Python: 3.7
CPU: ryzen 1700
GPU: gtx 1060 6gb, proprietary drivers

**Comment by gregzaal** [comment]
The latest version of Gaffer only works in Blender 2.8. You'll need to use an [older version](https://github.com/gregzaal/Gaffer/archive/v3.0.5.zip) (and disable the automatic updates) in order to use it in Blender 2.7x
