### ISSUE TITLE
Install failing from github release

### ISSUE THREAD

**Issue by ChildishGiant** [gregzaal/Gaffer#110]
https://gfycat.com/farflungachinggrosbeak
![](https://thumbs.gfycat.com/FarflungAchingGrosbeak-size_restricted.gif)
Installing release v3.1.2 on 2.8 doesn't work but also doesn't give an error. If I install with the b2.8 build from Blender market, I have no problems.

**Comment by gregzaal** [comment]
This is due to the way Github zips the source code - Blender expects the folder inside the zip file to be the same as the add-on name (`Gaffer`), but github names it according to the release (`Gaffer-3.1.2`).
