### ISSUE TITLE
Installation problems with 2.81 and 2.82 

### ISSUE THREAD

**Issue by andgeno** [gregzaal/Gaffer#112]
Hi,

I tried this addon with 2.81 and 2.82 and had problems with both of them.

**2.81**
Blender says it installed the addon successfully but it does not show up in the installed list.

**2.82**
Blender says it installed the addon successfully. When I try to enable the addon it throws an error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3'
```

**Comment by gregzaal** [comment]
It works for me in all versions of 2.8, including 2.83 Alpha from builder.blender.org.

Make sure it's installed to the correct location: `C:\Users\you\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Gaffer\__init__.py`

**Comment by Cornbrother** [comment]
I can confirm this is still an issue but that it is because the Gaffer-3-1-4 folder within the zip is labeled Gaffer-3.1.4. and blender takes exception to this. If you rename the folder to Gaffer-3-1-4 within the archive and install it then it works without incidence.

**Comment by gregzaal** [comment]
Or just rename the folder to `Gaffer` as I already said. Github names the zip file according to the version, nothing I can do about that. The version I upload to the blender market is correctly named and works immediately.

**Comment by andgeno** [comment]
Obviously a build error of the release zip files. It shouldn't require users to rename the content of an installable addon zip file.

**Comment by ChildishGiant** [comment]
I wonder if there's some way to make this show a custom error explaining the solution. I imagine not since the error is coming from blender itself. I know this could be fixed with GitHub actions or renaming the release items but I understand if you don't want to as this is a paid product. Legally talking you are allowed to not have the source publicly available, it just needs to be available to those who purchase the add-on IIRC.

**Comment by deadman49** [comment]
No matter what i rename the folder to "Gaffer-3.1.9" or "Gaffer-3-1-9 or "Gaffer", it was still popup issuse. I'm using blender 3.0.
