### ISSUE TITLE
Add an option to customize the tab

### ISSUE THREAD

**Issue by xan2622** [gregzaal/Gaffer#113]
Hi 

Could you please **add an option** (in the *add-on preferences*) **to give users the choice of the location for the tab where the addon is displayed**?
(in order to be able to move the add-on from its default tab to a custom one)

As you may already know, with more add-ons adding a new tab into the N panel, the later can easily become vertically overcrowded with many tabs.
Here is a related topic about this issue: https://blender.community/c/rightclickselect/dzdbbc/

Some users might want to move these tabs elsewhere (in "*Tools*" or "*Edit*" for example, or anywhere else).

Some add-ons already have this possibility and tbh, it's a very convenient option for the user.
I think that if most of addon developers consented to add this option, you (the devs) would succeed to fix “ *the N panel tabs clutter* ”. :+1:

---

You could have a look at these (free) add-ons, they already feature an option to customise the tab, maybe you could borrow the code to implement it into *Radial Array and Instances*.

**Backface Hiding** :  https://gitlab.com/ChameleonScales/Backface_Hiding

![6cb58ec90d0eaf2859819909e32075473fcd9f47](https://user-images.githubusercontent.com/1732773/79038461-b7cce680-7bd9-11ea-8eb7-97311b8566ba.jpeg)

**SpeedRetopo** : https://gumroad.com/l/speedretopo

![1173cda700ee4af649f858070ca426f970587afb](https://user-images.githubusercontent.com/1732773/79038462-bc919a80-7bd9-11ea-9d6f-d518dd2f198e.jpeg)

**Comment by gregzaal** [comment]
I agree this would be nice, will add it in the next release.
