### ISSUE TITLE
Make the gallery view detect folders as individual collections

### ISSUE THREAD

**Issue by mathewsamueldesign** [gregzaal/Gaffer#118]
Awesome HDRI plugin!

Is it possible to have subfolders to appear as individual collections in Gaffer? Right now it takes every folder and HDRI elements within them and dumps them into one large gallery. It would be great if it wasn't all in one large single gallery.

**Comment by gregzaal** [comment]
What would you use the subfolders for? Categorization? If that's the case, why not use the existing tags system to help you search for what you want?

**Comment by cerebralvision** [comment]
Yeah, it's for categorization. I'm going to try to create a UX flow for you so hopefully, it will help explain what I'm thinking of in a better way. The tag system works well too. I have to look into that option more. The auto-detection of folders as collections just saves a lot of time when trying to organize hundreds of HDRIs. I'll try to have a UX for ya within the Blender UI in the next few days. Hopefully, it will help and you can decide whether you think it's a good idea or not. Thanks =)
