### ISSUE TITLE
Error - Can't turn on Gaffer Add-on

### ISSUE THREAD

**Issue by CodyAtlanticer** [gregzaal/Gaffer#122]
![2020-10-26 19_40_09-Blender Preferences](https://user-images.githubusercontent.com/71175408/97168482-81486900-17c3-11eb-99c2-f696a51f38f6.png)

it took forever to turn on Gaffer add-on and there's an error said on the picture.

**Comment by CodyAtlanticer** [comment]
if anyone know this, just tell me, i'll close this issue

**Comment by ChildishGiant** [comment]
https://github.com/gregzaal/Gaffer/issues/112
