### ISSUE TITLE
Support for LuxCoreRender

### ISSUE THREAD

**Issue by Nicknroll** [gregzaal/Gaffer#124]
Hi
When i switching to Lux, Gaffer says that he support only Cycles, but since Luxcore works at cycles options too, can you please enable gaffer for other renderers? 

Thank you!
Nick

**Comment by gregzaal** [comment]
It's usually not so simple to enable compatibility, though I haven't used lux in years so I have no idea. I do have a poll that users vote on to determine which render engines I'll prioritize, so I'm closing this issue for now.
