### ISSUE TITLE
HDRI not working?

### ISSUE THREAD

**Issue by bbnavii** [gregzaal/Gaffer#126]
Hey so I have been having this issue for awhile now I was hoping it would eventually go away but it never did, I am on blender 2.9 

I am currently have 2 issues, one where im getting a pink screen and it says missing thumbnail and a second issue where the HDRI does not fully load and does not work at all

**Comment by gregzaal** [comment]
> it says missing thumbnail

Have you tried clicking the "Generate thumbnails" button?

> the HDRI does not fully load and does not work at all

I haven't heard of anyone else having this issue, so I'm going to need a lot more info in order to help you figure out what's wrong.

**Comment by bbnavii** [comment]
Yes, I clicked it and even went and refreshed the file itself, let me send some screneshots

**Comment by bbnavii** [comment]
https://i.gyazo.com/335cead5d49f8a57ad5232b586a1c45f.mp4

**Comment by bbnavii** [comment]
https://i.gyazo.com/e617119a1707586f42c044e67a3b088c.mp4

**Comment by gregzaal** [comment]
Seems like the hdr files you have might be corrupted, try downloading them again?
