### ISSUE TITLE
When I try to activate the addon, an error pops up: No module named "Gaffer-3"

### ISSUE THREAD

**Issue by raindropsfromsky** [gregzaal/Gaffer#130]
When I try to activate the addon, an error pops up: No module named "Gaffer-3"

Using Blender 3.0.0 Alpha, dated 24-Jun-2021, running on Windows 10 Home, 64 bits.

The latest version 3.1.8 has this problem. But if I use the trial link given below, it works.

**Comment by ChildishGiant** [comment]
Duplicate of #112
