### ISSUE TITLE
3.1.9 3.0 not installing

### ISSUE THREAD

**Issue by AlexFundorin** [gregzaal/Gaffer#136]
Could be me, but after removing 3.1.8 and installing 3.1.9, I'm getting this error:
![image](https://user-images.githubusercontent.com/22612802/145970799-82f2f9d2-4b16-4961-9ca4-65ab35e8390a.png)

**Comment by AlexFundorin** [comment]
Seems like it has something to do with my python installation.

**Comment by gregzaal** [comment]
Duplicate of #112
