### ISSUE TITLE
Solo should respect existing ray visibility settings.

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Gaffer#139]
> Step 1: I turn off Camera option in Ray Visibility to hide the HDRI photo (but keep other light settings).
> 
> Step 2: I solo a light.
> 
> Step 3: I unsolo that light.
> 
> Result: All settings in Ray Visibility are now checked, even Camera (which was previously disabled).
> 
> Expectation: All settings in Ray Visibility stay the same as they're before the solo. (Camera stay unchecked in this case)

**Comment by lekima** [comment]
Hi Greg,

It'd be great if the World's visibility toggle also respects existing Ray Visibility settings, currently toggling this will also reset everything in Ray Visibility.

![image](https://user-images.githubusercontent.com/1571302/147159322-202c3aac-cfd3-4b1e-91b7-b64398f80cc5.png)
