### ISSUE TITLE
OFFTOPIC [Feature Request] Node Wrangler OMR support

### ISSUE THREAD

**Issue by AlexFundorin** [gregzaal/Gaffer#140]
Sorry for hijacking your other addon's issue tracker, but I've been wondering if it's possible to add OMR (Occlusion, Metallness, Roughness) type of textures support to the node wrangler addon? 
Is there any other official place where I can discuss node wrangler?

**Comment by gregzaal** [comment]
Node Wrangler is a part of Blender's core codebase, which means you can discuss it on the official channels and forums. I don't maintain it myself currently.
