### ISSUE TITLE
Lights Refresh 

### ISSUE THREAD

**Issue by Dandiboy** [gregzaal/Gaffer#147]
**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser :chrome
 - Version blender .3.1.2
 - Gaffer 3.1.11
The lights do not update automatically.(need to refresh)
The lights Hide/Show  Toggle option hide in viewport and render. Cant toggle after that .disappear from the tab menu.

**Comment by gregzaal** [comment]
> The lights do not update automatically.(need to refresh)

This is by design, it's not currently possible for Gaffer to detect when you create or delete lights without a massive performance hit. Sorry.

> The lights Hide/Show Toggle option hide in viewport and render. Cant toggle after that .disappear from the tab menu.

I don't understand what you mean, sorry. Please provide a step-by-step list of how I can reproduce your issue and explain what you expected to happen.

**Comment by Dandiboy** [comment]
Sorry it was my mistake . I had the  Visible Lights Only  activated .
