### ISSUE TITLE
Warmth isn't working anymore

### ISSUE THREAD

**Issue by AlexFundorin** [gregzaal/Gaffer#148]
Tested in 3.3 Alpha with Gaffer 3.1.11
Adjusting "warmth" turns hdri light completely off. It's because the warmth node group is using separate/combine RGB nodes, which were ditched in 3.3 in favor of XYZ.

**Comment by gregzaal** [comment]
@AlexFundorin It's working fine for me, could you try completely removing all Gaffer files and installing it again?
