### ISSUE TITLE
Support of Light Groups

### ISSUE THREAD

**Issue by Nickonimus** [gregzaal/Gaffer#153]
Hi
I'd like to ask an improvement to add Light Groups support for Gaffer. It would be handy to keep all light settings in one place, since blender mess it by default. Also would be great to have some automation, add all lights instances to one LG in single click, create auto Light Groups etc.

**Comment by gregzaal** [comment]
Partial support for light groups was added in `3.1.18` (see [change log](https://blendermarket.com/products/gaffer-light-manager)), otherwise let's merge this issue with #160 for feature requests related to light groups.
