### ISSUE TITLE
Blender 3.6, python errors and some HDRI's not updating. 

### ISSUE THREAD

**Issue by CharlesErnst** [gregzaal/Gaffer#159]
***PLEASE NOTE***
If you did not purchase Gaffer, I cannot provide you any user support. This especially includes helping you install the add-on correctly. Check #112 (https://github.com/gregzaal/Gaffer/issues/112) if you are having installation problems.

----

**Describe the bug**
When browsing HDRI some load other do not. They work in Blender 3.4.

**To Reproduce**
1. Enable HDRI
2. Browse to desired HDRI select it
3. Still shows last HDRI on screen
4. click on multiple HDRI images some load others do not.
5. Went into addon dialog to refresh images.
Throws python errors.

![gaffer](https://github.com/gregzaal/Gaffer/assets/5787850/aa1fab40-1414-4ebe-806f-c80b3457b234)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version 3.6
 - Gaffer Version 3.1.18

**Comment by gregzaal** [comment]
Hi there, sorry for the troubles.

I'm unable to reproduce this problem following your instructions, everything seems to be working fine to me. Perhaps your files are corrupt somehow? Perhaps try drag that exact file (`yaris_interior_garage_4k.hdr`) into an image editor in Blender and see if you also struggle there.
