### ISSUE TITLE
Addon doesn't respect the choosen resolution

### ISSUE THREAD

**Issue by AlexFundorin** [gregzaal/Gaffer#165]
Latest release.

There are several resolutions of the same HDRI. When the user selects, let's say 4k version, it's used fine. But, once he disables the addon and enables it again, the texture variant is reset to the first one in the list, which is 1k, usually.

**Comment by gregzaal** [comment]
Hi Alex, this is by design. You may want to use the same HDRI at various resolutions in multiple projects, so we stick to the default of 1k to start with.
