### ISSUE TITLE
Describe the bug:

### ISSUE THREAD

**Issue by roeks001** [gregzaal/Gaffer#166]
***PLEASE NOTE***
If you did not purchase Gaffer, I cannot provide you any user support. This especially includes helping you install the add-on correctly. Check #112 (https://github.com/gregzaal/Gaffer/issues/112) if you are having installation problems.

----

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Blender Version [e.g. 3.3]
 - Gaffer Version [e.g. 3.1.14]

**Additional context**

**Comment by roeks001** [comment]
Describe the bug:
When I try to enter the HDRI filepath for in Blender -> Preferences -> Addons for Gaffer, it gives me error codes and the file path does not work.
Issue persists regardless of Cycles or Eevee.

To Reproduce:
1. Open Blender
2. Click on Edit in the top left corner
3. Click on Preferences
4. Click on Addons
5. Enable Gaffer and expand the list
6. In the Preferences section of Gaffer, click on the folder button on the right side of the panel
7. Select your folder
8. After you have selected your folder, an error message should appear.

Expected Behaviour:
The expected behaviour is that after I have chosen the HDRI folder, the HDRIs within the folder will be selectable from within Blender.

Screenshots:
![image](https://github.com/gregzaal/Gaffer/assets/74716313/ccbe2a91-893e-4334-8841-c593ff3fe833)

Desktop:
Windows 11
Blender 4.1
Gaffer 3.2.0

**Comment by gregzaal** [comment]
Thanks for the report, fixed in v3.2.1.
