### ISSUE TITLE
Activating the addon in Blender 4.0 give errors!

### ISSUE THREAD

**Issue by merecesarchviz** [gregzaal/Gaffer#167]
hi

I install the addon but when i try to activate it in the addon settings give me errors! any idea what is happen!?

![errrrrr](https://github.com/gregzaal/Gaffer/assets/79140456/89737791-5e31-43c9-8141-f116839d89a6)

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/poly-haven-asset-browser) or supporting us on [Patreon](https://www.patreon.com/polyhaven/overview), make sure you follow the installation instructions in the readme carefully. The add-on must be downloaded from the releases page.
