### ISSUE TITLE
Error while enabling the addon in Blender 4.1.1

### ISSUE THREAD

**Issue by dimasddim** [gregzaal/Gaffer#170]
**Describe the bug**
Cannot enable the addon

**To Reproduce**
1. Go to 'Installed addon'
2. Click on 'check the box to enable'
3. Error occured

**Expected behavior**
Addon enabled

**Screenshots**
<img width="588" alt="blender_foYRGqkN0g" src="https://github.com/gregzaal/Gaffer/assets/20833397/5767b921-946c-4f1c-af8a-bb67f476c5df">

**Desktop (please complete the following information):**
 - OS: Windows 11 2H22
 - Blender Version 4.1.1
 - Gaffer Version 3.2.0

**Comment by gregzaal** [comment]
Hi, if you're not purchasing the add-on from the [Blender Market](https://blendermarket.com/products/gaffer-light-manager), make sure you follow the installation instructions in the readme carefully (download with the provided link, not the whole git repository).

**Comment by dimasddim** [comment]
Well, that fixed the error. My apologies for the inconvenience.
