### ISSUE TITLE
Gaffer Not working if polyheaven asset library not present

### ISSUE THREAD

**Issue by thehyenaman** [gregzaal/Gaffer#173]
Installing Gaffer on a clean Blender 4.1 on Windows can't detect HDRI folder.

In functions.py at line 832, it tries to pass a None to os.path.normpath which doesn't work.

adding. 

```
    if p1 == None:
        return os.path.normcase(os.path.normpath(p2))
```
to line 832 fixes the problem. Or change the return value of the function `polyhaven_asset_lib ` from None to a str or something. Sorry couldn't add a pull request or if there was something I did wrong but thought it might help someone.

**Comment by gregzaal** [comment]
What version of Gaffer are you using? I believe this issue was fixed in f6dff37b (v.3.2.1).

**Comment by thehyenaman** [comment]
Ohh, I just downloaded the latest version from the release tabs. It still points to 3.2.0

**Comment by thehyenaman** [comment]
Ohh, I just downloaded the latest version from the release tabs. It still points to 3.2.0.
