### ISSUE TITLE
Show selected light's view in the viewport

### ISSUE THREAD

**Issue by DarkCellar** [gregzaal/Gaffer#22]
Here's an enhancement idea. Select a light in Gaffer and have a function that switches a viewport to that light's view angle in the scene. And switch back, of course.

Thanks,

-Mitch

**Comment by gregzaal** [comment]
You can already do this by pressing Ctrl-Numpad0 with a light (or any object) selected, and then enabling Lock Camera to View.

![](http://i.imgur.com/0PwnXN2.png)

I could possibly add a button for (slightly) quicker access to this, but it might clutter up the UI so I'm not sure. Some extra improvements could be made to this, like showing some visualization of the spot lamp's cone, size, blend, etc.

**Comment by DarkCellar** [comment]
That totally makes sense. Definitely wouldn't want a cluttered interface. I suggested because I always forget the hotkey. LOL.

I do like the idea of enhanced visualization. Thanks for even considering.

**Comment by gregzaal** [comment]
The enhanced visualization could perhaps even be done automatically by trying to detect if the user is using a lamp as the camera, I'll play around a bit :)

**Comment by DarkCellar** [comment]
That would be cool. Thanks! BTW, Gaffer is an essential plugin for me. Love it!

**Comment by gregzaal** [comment]
The view distance when using a lamp as a camera seems to be hard coded to only 40 units with no way (that I can find) to increase this. This distance is way too short in a lot of cases, so it's basically useless.
