### ISSUE TITLE
HDRIs: Searching

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Gaffer#26]
Have a search box above the HDRI picker that matches both name and tags.

Tags for each can be inputted manually, or in the case of HDRI Haven stuff just downloaded.

**Comment by blenderskool** [comment]
I was working on this, but I wonder how can tags be saved

**Comment by gregzaal** [comment]
I've got something in mind, let me take care of it :)

**Comment by blenderskool** [comment]
👍
