### ISSUE TITLE
Bring back the actual World Nodes if HDR is disabled

### ISSUE THREAD

**Issue by blenderskool** [gregzaal/Gaffer#37]
I think it would be useful that when the HDR is disabled, the world material is brought back to how it was before

**Comment by gregzaal** [comment]
True, wasn't sure how to handle disabling but this sounds like a good idea.

**Comment by blenderskool** [comment]
Another tiny fix would be to actually switch to Cycles when HDRI is enabled if user is not in Cycles.

**Comment by gregzaal** [comment]
Hmm, I don't think that's a good idea, rather just hide the HDRI panel altogether if they're not using Cycles.

**Comment by blenderskool** [comment]
While it may be a good idea to hide the entire panel but if a new user sees there is no HDRI Panel, then he would think that there is some problem. Mostly there should be a message that can just inform the user that it works in Cycles only 😃

**Comment by gregzaal** [comment]
I think since Blender Render doesn't have good HDRI support, people don't use it for that and thus won't assume this panel should be there too. Rather not clutter up the UI just to say this.
