### ISSUE TITLE
Proper Implementation of Loading Custom icons

### ISSUE THREAD

**Issue by blenderskool** [gregzaal/Gaffer#49]
Since the add-on has started using many custom icons..... it adds up to memory usage, and therefore I was conducting a small test of activating-deactivating add-on too many times, fast and continuous.... and Blender crashed.
This is because custom icons are not properly loaded. I checked retopoflow add-on which also uses custom icons, and this problem does not occur there.

Really minor thing just thought to inform you 😃

**Comment by gregzaal** [comment]
I couldn't reproduce this - how do you know it's caused by custom icons?

**Comment by blenderskool** [comment]
I found it out when I was using custom icons in my add-on. Here is a gif that can show what I mean [http://imgur.com/a/y9jbl](http://imgur.com/a/y9jbl)

**Comment by gregzaal** [comment]
Are you using the latest blender master? What OS?

**Comment by blenderskool** [comment]
Yes, I used the latest add-on, using Blender 2.78a on Windows 10

**Comment by gregzaal** [comment]
Could you try with a newer build of blender from builder.blender.org ? I seem to remember something about memory leaking icons, might have been a bug that got fixed.

**Comment by blenderskool** [comment]
I tried the latest build, works fine 👍

**Comment by gregzaal** [comment]
Excellent!
