### ISSUE TITLE
Allow rotation of HDRI background separate from lighting

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Gaffer#55]

**Comment by gregzaal** [comment]
This is a bit more of a can of worms than anticipated as the image node (and the whole chain of nodes after it) would need to be duplicated.

**Comment by xan2622** [comment]
Maybe the code of this add-on could help?
https://gumroad.com/l/XQYEl

**Comment by gregzaal** [comment]
The dragging hotkey in the interface is cool, but from what I can tell from that page it just rotates a single mapping node (what gaffer already does with the rotation slider). What this task is about is doing that separately for the world visible to the camera and visible to the rest of the scene (for lighting and reflections).
