### ISSUE TITLE
Crash halfway through thumbnail generation.

### ISSUE THREAD

**Issue by SolarPolarMan** [gregzaal/Gaffer#62]
I assume this is because I have .exr HDRIs in my folder and my blender crashes every time it tries to generate thumbnails. Blender can use them so I don't want to get rid of them.

**Comment by gregzaal** [comment]
This seems to happen inconsistently for some people, I haven't been able to reproduce it. Does it crash on a particular file or just in a different place each time?

Try clicking 'Generate Thumbnails', waiting for it to crash, and then trying to generate them again. Do this a couple times until either you know exactly which file(s) cause it to crash, or it manages to finish generating them.

EXRs are fully supported, it shouldn't make a difference.

**Comment by SolarPolarMan** [comment]
I recorded it running and it always crashes when trying to generate a thumbnail for ["Mono_Lake_C"](https://drive.google.com/open?id=0B4y8m8hDaMDYTUI1NEhWVkVBVms) (Download linked). It doesn't crash when generating one for Mono_Lake_B which is from the same creator and is packaged the same way.

**Comment by gregzaal** [comment]
Just tried with that same file (the whole folder actually) and it crashed once, but didn't crash 
the second time I tried. Strangely, the thumbnail it generated is all screwed up:

![mono_lake_c__thumb_preview](https://cloud.githubusercontent.com/assets/5604661/23223680/5b8dc586-f934-11e6-826a-1ee8ad16466b.jpg)

I suppose it's using one of the JPG files and getting confused about the number of channels per pixel, though I don't think that's a related issue.

Testing again now and it does keep crashing, so thanks I'll investigate and make a [bug fix release](https://github.com/gregzaal/Gaffer/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3Av3.0.1%20) soon.

**Comment by gregzaal** [comment]
For now you can just copy that `Mono_Lake_C_Thumb.jpg` file to Gaffer's data folder (`C:\Users\name\AppData\Roaming\Blender Foundation\Blender\data\gaffer\thumbs` on windows, or press Spacebar in Blender and search for the "Open Gaffer's Data Folder" operator) and rename it to `mono_lake_c__thumb_preview.jpg`.

**Comment by SolarPolarMan** [comment]
Looking at AppData\Roaming\Blender Foundation\Blender\data\gaffer\thumbs\ I also have some corrupted thumbnails, including "malibu_overlook__thumb_preview"
![malibu_overlook__thumb_preview](https://cloud.githubusercontent.com/assets/13716824/23226097/4d5ba7ce-f92c-11e6-9cec-a0a9ae97eb1b.jpg) from one of your HDRIs

**Comment by SolarPolarMan** [comment]
Oops but yes. ![image](https://cloud.githubusercontent.com/assets/13716824/23228327/123eed2e-f934-11e6-8255-ee5cd38796cb.png)

**Comment by gregzaal** [comment]
Great, then at least we know what the problem is :)

**Comment by gregzaal** [comment]
@SolarPolarMan I think I've fixed this now, can you test it?

1. Remove Gaffer from the User Preferences
2. Download and install [this Zip](https://github.com/gregzaal/Gaffer/archive/master.zip)

If you have trouble installing it again, locate the folder where Blender add-ons are stored on your system (typically `C:\Users\yourname\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons`) and make sure the Gaffer folder is named `Gaffer` and not `Gaffer-master` or something else.

You can delete the old broken thumbnails in `C:\Users\yourname\AppData\Roaming\Blender Foundation\Blender\data\gaffer\thumbs`.
