### ISSUE TITLE
Error when trying to enable Gaffer

### ISSUE THREAD

**Issue by roofoo** [gregzaal/Gaffer#78]
![screen shot 2017-03-11 at 8 56 22 pm](https://cloud.githubusercontent.com/assets/26353870/23828372/5baa630a-069d-11e7-8053-44248cc7061c.png)
This is in Blender 2.78c on Mac OS 10.11.6

**Comment by gregzaal** [comment]
There was a problem with the initial OSX build of Blender 2.78c, just [download it again here](https://www.blender.org/download/) and it should work.
