### ISSUE TITLE
RNA Warning

### ISSUE THREAD

**Issue by VaclavC** [gregzaal/Gaffer#80]
I'am getting 

`RNA Warning: Current value "0" matches no enum in 'GafferProperties', '', 'hdri'
`

warnings into console, when Gaffer is installed.

**Comment by gregzaal** [comment]
Thanks for the report - this is a minor bug that shouldn't affect the functionality of Gaffer, so I'll put it off until the next minor release (3.1)

**Comment by gregzaal** [comment]
There isn't a simple way to get rid of these warnings, and they're completely harmless, so I'm closing this and don't plan on doing anything about it any time soon :)
