### ISSUE TITLE
Gaffer not listed in Blender because of "." in folder name

### ISSUE THREAD

**Issue by akej74** [gregzaal/Gaffer#81]
Hi, 

I downloaded Gaffer 3.0.2 (from GitHub) to try it out and noticed that it did not show up in the list of addons in Blender after installing (from ZIP file). The ZIP file was extracted automatically to "...\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Gaffer-3.0.2" and everything looked OK. 

I found [this bug report](https://developer.blender.org/T47651) stating that addons with "." in the folder names will not show up. I changed the name to ".../Gaffer-302" and then it worked.

Just like to let you know this; maybe you could mention this in the installation instructions...? I'm not sure if this affects the version from Blender Nation, but I will for sure make a purchase as this is a really nice addon.

**Comment by gregzaal** [comment]
Ah thanks for letting me know, I wondered why it did not work straight from github. The version on the Blender Market is packed manually as Gaffer.zip, so that works fine.
