### ISSUE TITLE
How to enable the "Control background separately" feature?

### ISSUE THREAD

**Issue by akej74** [gregzaal/Gaffer#87]
Hi Greg,

When I try to adjust the sliders under "Control background separately", I see no changes to the HDRI background in my render. The sliders seems to be "dimmed" as well, but it is possible to change the values.

Sorry to bother you with this question, it's most likely a user error from my side... I suspect I have changed something somewhere in Blender I shouldn't have touched :-), but maybe you  can give me some idea on what to try? I'm using latest version of Gaffer with Blender 2.79 official release.

**Comment by gregzaal** [comment]
Hey - you first need to enable the override by clicking on the button to the left of the slider:

![2017-12-10_10-35-46_blender](https://user-images.githubusercontent.com/5604661/33803327-f858357c-dd95-11e7-9551-11728b1867e0.png)

I guess this is not obvious, I could perhaps change it to simple checkboxes instead.

**Comment by akej74** [comment]
Thanks for a quick reply, it works, sorry for the confusion :-)
