### ISSUE TITLE
Missing advanced panel on 2.79.5

### ISSUE THREAD

**Issue by Acrivec** [gregzaal/Gaffer#90]
The advanced panel where you can pick the high-jpg resolution reflections and background customization is missing in 2.79.5 experimental builds. On 2.79 it worked properly. 
I've also noticed that in 2.79 I had a button to download HDRIs, on 2.79.5 it never showed up. 

![3eu6jmy 1](https://user-images.githubusercontent.com/26365504/42932623-15d8c642-8b43-11e8-97d8-a9d3d78310f6.png)

**Comment by gregzaal** [comment]
Fixed in 97d814d6

**Comment by ChildishGiant** [comment]
DAMN! That was a fast fix! Best £15 in ages!

**Comment by Acrivec** [comment]
@ChildishGiant it's because I used my trap card ʕ•ᴥ•ʔ 
![ykpj9dj 1](https://user-images.githubusercontent.com/26365504/42940041-531987a2-8b58-11e8-9ca3-5245506f76c0.png)
