### ISSUE TITLE
Continue this

### ISSUE THREAD

**Issue by paperbenni** [gregzaal/Gaffer#93]
Can you please continue developing this addon. I'm a huge fan of it and it is the only option available for those who don't want to buy pro lighting skies. It would be such a shame if this wouldn't get developed further. For example a search bar would be insanely useful

**Comment by gregzaal** [comment]
I plan to :) There is already a search bar at the top of the HDRI panel, and I publish two new HDRIs every single week on hdrihaven.com (which admittedly could use better integration with gaffer).

**Comment by paperbenni** [comment]
Thanks, I never noticed the searchbar
